// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://ardianrawk.blogspot.com/2017/04/kata-bijak-vino-g-bastian.html")
    await driver.manage().window().setRect(1382, 744)
    await driver.findElement(By.linkText("Kartu Lipat")).click()
    await driver.findElement(By.css(".close > img")).click()
    await driver.findElement(By.css(".group:nth-child(2)")).click()
    await driver.findElement(By.css(".group:nth-child(3)")).click()
    await driver.findElement(By.css(".group:nth-child(4)")).click()
    await driver.findElement(By.linkText("Majalah")).click()
  })
})
