// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://dev.tempramas.divmu.pindad.co.id/home")
    await driver.manage().window().setRect(1050, 708)
    await driver.findElement(By.linkText("9")).click()
    await driver.findElement(By.linkText("5.56")).click()
    {
      const element = await driver.findElement(By.linkText("7.62"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.linkText("7.62"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.linkText("7.62"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.linkText("7.62")).click()
    await driver.findElement(By.linkText("12.7")).click()
    await driver.findElement(By.linkText("Data History")).click()
    await driver.findElement(By.linkText("Admin")).click()
    await driver.findElement(By.css(".arrow")).click()
    await driver.findElement(By.css(".huge")).click()
    await driver.findElement(By.css(".huge")).click()
    await driver.findElement(By.css(".huge")).click()
  })
})
