// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://video.divmu.pindad.co.id/")
    await driver.manage().window().setRect(1050, 708)
    await driver.findElement(By.css(".breadcrumbs")).click()
    await driver.findElement(By.name("loginbtn")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("deby")
    await driver.findElement(By.css(".login-fields:nth-child(3)")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("p")
    await driver.findElement(By.css(".button:nth-child(4)")).click()
    await driver.findElement(By.linkText("Home Page")).click()
    await driver.findElement(By.name("signupbtn")).click()
    await driver.findElement(By.id("jform_name")).click()
    await driver.findElement(By.id("jform_name")).sendKeys("deby")
    await driver.findElement(By.id("jform_username")).click()
    await driver.findElement(By.id("jform_username")).sendKeys("deby")
    await driver.findElement(By.id("jform_password1")).click()
    await driver.findElement(By.id("jform_password1")).sendKeys("peng")
    await driver.findElement(By.id("jform_password2")).click()
    await driver.findElement(By.id("jform_password2")).sendKeys("peng")
    await driver.findElement(By.id("jform_email1")).click()
    await driver.findElement(By.id("jform_email1")).sendKeys("deb@gmail.com")
    await driver.findElement(By.id("jform_email2")).click()
    await driver.findElement(By.id("jform_email2")).sendKeys("deb@gmail.com")
    await driver.findElement(By.css(".validate")).click()
    {
      const element = await driver.findElement(By.css(".mod_hdvideoplayer img"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".mod_hdvideoplayer img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".mod_hdvideoplayer img"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".mod_hdvideoplayer img")).click()
    await driver.findElement(By.css(".clearfix:nth-child(1) > .categories_video:nth-child(2) .info_hover > img")).click()
    await driver.findElement(By.css(".mod_hdvideoplayer img")).click()
    await driver.findElement(By.id("searchtxtbox")).click()
    await driver.findElement(By.id("searchtxtbox")).sendKeys("humor")
    await driver.findElement(By.id("search_btn")).click()
  })
})
